const typeEnum = {
  Polo: 'Polo Shirt',
  Dress: 'Dress',
  Hoodie: 'Hoodies',
  TShirt: 'T-Shirt',
  Flipflop: 'Flip-flops',
  Shorts: 'Shorts',
  Skirt: 'Skirt',
  Jeans: 'Jeans',
  Shoes: 'Shoes',
  Coat: 'Coat',
  HighHeels: 'High-heels',
  Suit: 'Suit',
  Cap: 'Cap',
  Socks: 'Socks',
  Shirt: 'Shirt',
  Bra: 'Bra',
  Scarf: 'Scarf',
  Swimsuit: 'Swimsuit',
  Hat: 'Hat',
  Gloves: 'Gloves',
  Sunglasses: 'Sunglasses',
  LeatherJacket: 'Leather Jacket',
  Sweater: 'Sweater',
  GymWear: 'Gym wear',
  Tie: 'Tie',
};
